/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp dee-shared-model.xml -p libQtDee/dee-shared-model-proxy
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DEE-SHARED-MODEL-PROXY_H_1286371347
#define DEE-SHARED-MODEL-PROXY_H_1286371347

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.canonical.Dee.Model
 */
class ComCanonicalDeeModelInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.canonical.Dee.Model"; }

public:
    ComCanonicalDeeModelInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ComCanonicalDeeModelInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> Clone()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Clone"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace canonical {
    namespace Dee {
      typedef ::ComCanonicalDeeModelInterface Model;
    }
  }
}
#endif
