debian/unity-2d.py /usr/share/apport/general-hooks
gconf/* /usr/share/gconf
session/unity-2d.desktop /usr/share/xsessions
session/2d-ubuntu.session /usr/share/gnome-session/sessions
debian/20_unity-2d-gconf-mandatory /usr/share/gconf/unity-2d/mandatory
debian/20_unity-2d-gconf-default /usr/share/gconf/unity-2d/default
xdg/applications.menu /etc/xdg/xdg-unity-2d/menus
xdg/settings.menu /etc/xdg/xdg-unity-2d/menus
