etc/xdg/xdg-unity-qt/autostart/unity-qt-launcher.desktop
usr/bin/unity-qt-launcher
usr/share/unity-qt/Application.qml
usr/share/unity-qt/Launcher.qml
usr/share/unity-qt/artwork
usr/share/unity-qt/artwork/glow.png
usr/share/unity-qt/artwork/shadow.png
usr/lib/qt4/imports/UnityApplications/libUnityApplications.so.1
usr/lib/qt4/imports/UnityApplications/libUnityApplications.so.1.0.0
usr/lib/qt4/imports/UnityApplications/qmldir
usr/lib/qt4/imports/UnityApplications/libUnityApplications.so

