#!/bin/sh
set -e
PROGNAME=$(basename $0)

die() {
    echo "$PROGNAME: ERROR: $*"
    exit 1
}

usage() {
    echo "Usage: $PROGNAME <path/to/po/dir>"
    exit 1
}

if [ $# -ne 1 ] ; then
    usage
fi

PO_DIR=$1

if [ ! -d "$PO_DIR" ] ; then
    die "$PO_DIR does not exist or is not a directory"
fi

cd $PO_DIR
PO_DIR=$PWD

# Create a list of files to scan
UPDATE_POT_DIR=$(mktemp --tmpdir -d unity-2d-update-pot.XXXXX)
trap 'rm -rf "$UPDATE_POT_DIR"' EXIT
bzr export $UPDATE_POT_DIR
cd $UPDATE_POT_DIR
find -name '*.cpp' > lst
find -name '*.qml' >> lst

# Generate pot from our list
xgettext \
    --output $PO_DIR/unity-2d.pot \
    --files-from lst \
    --qt --c++ \
    --keyword=tr --keyword=qsTr \
    --package-name unity-2d \
    --copyright-holder "Canonical Ltd" \
    --msgid-bugs-address "https://bugs.launchpad.net/unity-2d/+filebug"

echo "$PROGNAME: $PO_DIR/unity-2d.pot updated"
