.TH unity-2d-shell 1
.SH NAME
unity-2d-shell \- Unity 2D Shell
.SH SYNOPSIS
.B unity-2d-shell [-opengl] [-rootqml File.qml]
displays some components of Unity 2D. It contains the launcher and dash.
It functions as part Unity 2D, and is not meant to be used as a standalone
application.
It can however be used for testing or prototyping of only specific components
of Unity 2D by using the rootqml argument.
.SH OPTIONS
.TP
\fB\-opengl\fR
Run the application using an openGL-enabled widget
.TP
\fB\qmlfile\fR
The path of a QML file to load instead of the full shell
