.TH unity-2d-launcher 1
.SH NAME
unity-2d-launcher \- Provides launcher sidebar in the Unity 2D environment
.SH SYNOPSIS
.B unity-2d-launcher
provides the launcher sidebar for the Unity 2D launcher, which provides the
icons and application switcher. It is meant to be used as the full Unity 2D
environment
.SH OPTIONS
.TP
This application takes no arguments.

