.TH unity-2d-places 1
.SH NAME
unity-2d-places \- Unity 2D Places
.SH SYNOPSIS
.B unity-2d-places
displays a top panel containing the application menu and various indicators.
It functions as part Unity 2D, and is not meant to be used as a standalone
application.
.SH OPTIONS
.TP
This application takes no arguments.

