.TH unity-2d-spread 1
.SH NAME
unity-2d-spread \- Unity 2D Spread
.SH SYNOPSIS
.B unity-2d-spread
spread allows you to display a quick thumbnailed view of open windows so you
can quickly and effectively choose which one you want to switch to. It
functions as part of Unity 2D, and is not meant to be used as a standalone
app
.SH OPTIONS
.TP
This application takes no arguments.

